### ISSUE TITLE
PKR is missing!

### ISSUE THREAD

**Issue by ahmadawais** [exchangeratesapi/exchangeratesapi#19]
Love the service. But `PKR` currency is missing. Any chance you can add that?

**Comment by acs-ferreira** [comment]
Only rates/currency's published at https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html are supported.

**Comment by ahmadawais** [comment]
That's sad. Thank you.
