### ISSUE TITLE
Is this project dead now?

### ISSUE THREAD

**Issue by oviliz** [exchangeratesapi/exchangeratesapi#20]
Is not working anymore for me and the website says "Invalid website" :(
![screenshot from 2018-08-24 00-06-23](https://user-images.githubusercontent.com/73616/44556422-97fd5c00-a731-11e8-8941-b3581a98a33b.png)

**Comment by acs-ferreira** [comment]
API is up and running: https://api.exchangeratesapi.io/latest?base=USD

The message "Invalid website" has nothing to see with the service, it is about the Live Chat Module miss-configured.

**Comment by WingYn** [comment]
The endpoint changed from this one? https://exchangeratesapi.io/api/

**Comment by brian-from-quantrocket** [comment]
I'm also seeing that https://exchangeratesapi.io/api/, which worked until yesterday, returns 404 as of today. Any chance you can post a deprecation warning to the README or website before removing an endpoint? Or maybe I missed the warning?

**Comment by brian-from-quantrocket** [comment]
Better yet, any chance you could restore the earlier endpoint for a few weeks to allow time to update applications to the new endpoint?

**Comment by Wilhelm1994** [comment]
I have the same issue with 404 since yesterday at 1pm America/Eastern time.

**Comment by WingYn** [comment]
The endpoint got changed, you can see it in the git commit history. I wonder why it just suddenly changed though.

**Comment by chase-moskal** [comment]
to be extra clear,

**problem:** requests to the following api url have stopped working

- https://exchangeratesapi.io/api/latest

**solution:** point your application to this url instead

- https://api.exchangeratesapi.io/latest

**Comment by madisvain** [comment]
This project is live and well. I have an agreement to keep the service running and monitor everything so there will be no more interruptions to this service.

**Comment by oviliz** [comment]
@madisvain is this project still going? Asking simply because the last commit was 2 years ago.

**Comment by lucasRolff** [comment]
@oviliz exchangeratesapi.io got acquired out of the blue by apilayer.

For the codebase itself, I'm not sure what you expect to be committed. The ECB XML continues to be the same.

**Comment by madisvain** [comment]
Hello @oviliz and @lucasRolff 

Yes thats true - the agreement was to keep the service free and running after the acquirement by apilayer but as it seems it's been converted to a paid solution.

As I still needed a solution to provide my store visitors with geolocation & currencies then I'm currently running a similar API (which will never be sold!). You can check it out and I'm pretty sure it will fill your needs.

Website: https://vatcomply.com
Docs: https://vatcomply.com/documentation
Github: https://github.com/madisvain/vatcomply
Currency API: https://api.vatcomply.com/rates

**Comment by lucasRolff** [comment]
> Hello @oviliz and @lucasRolff
> 
> Yes thats true - the agreement was to keep the service free and running after the acquirement by apilayer but as it seems it's been converted to a paid solution.
> 
> As I still needed a solution to provide my store visitors with geolocation & currencies then I'm currently running a similar API (which will never be sold!). You can check it out and I'm pretty sure it will fill your needs.
> 
> Website: https://vatcomply.com Docs: https://vatcomply.com/documentation Github: https://github.com/madisvain/vatcomply Currency API: https://api.vatcomply.com/rates

I personally ended up building my own, which is fully geo-replicated in 15 locations 😆  I don't trust "free" products, since we've seen what happened already once.
