### ISSUE TITLE
Historic data

### ISSUE THREAD

**Issue by gmmoraes** [exchangeratesapi/exchangeratesapi#23]
Is there any way to get the exchange rates for an specifc date period?

By the URL below I am able to get the exchange rate for USD and BRL for the date of 2018-09-12, would there be any way to get these exchanges rate from 2018-09-12 until 2018-09-19 for example?

https://api.exchangeratesapi.io/2018-09-12?symbols=USD,BRL

**Comment by madisvain** [comment]
@gmmoraes I think this would be possible - I can look into this feature for you over the weekend and give you feedback

**Comment by gmmoraes** [comment]
@madisvain , thank you!

**Comment by madisvain** [comment]
@gmmoraes I have implemented the history download for date ranges.

The current API is something like this:
https://api.exchangeratesapi.io/history?start_at=2018-01-01&end_at=2018-09-01&base=USD&symbols=ILS,JPY

The is preliminary. I do not expect big changes to the parameters. But we might have to limit the maximum period you can ask for to maybe one year.

What is your current use case for this history API call so I could take this into account?

Please let me know what you think and give feedback on this functionality.

**Comment by gmmoraes** [comment]
@madisvain Thank you and my apologies for the late reply.

The feature work perfectly!
My goal with the historical data is to get the exchange rate between US Dollar and Brazilian Real for the current month.(repeating every month)

**Comment by gmmoraes** [comment]
@madisvain , would there be the possibility of orderning the results by their date (ascending or descending) and get only the final exchange rate for each month?

**Comment by madisvain** [comment]
@gmmoraes ordering will be added - sorry this was my mistake it was not already there. Can you explain a bit about the final exchange rate for each month. What do you mean by that?

**Comment by gmmoraes** [comment]
Thanks!
Instead of getting a response with the exchange rate for each day of the month, would there be the possibility of getting a response with the "average exchange rate" for each month of the timeframe or the exchange rate for the last day of each month?

**Comment by madisvain** [comment]
The rates are ordered_by date ASC:
https://github.com/exchangeratesapi/exchangeratesapi/blob/master/exchangerates/app.py#L207

The README has been updated with the following request examples:
Get historical rates for a time period.

```http
GET /history?start_at=2018-01-01&end_at=2018-09-01
```

Limit results to specific exchange rates to save bandwidth with the symbols parameter.

```http
GET /history?start_at=2018-01-01&end_at=2018-09-01&symbols=ILS,JPY
```

Quote the historical rates against a different currency.

```http
GET /history?start_at=2018-01-01&end_at=2018-09-01&base=USD
```

@gmmoraes I'm sorry but the current API will not be providing such specific functionality. This can already be calculated client/server side after fetching either the time series data or the last day of the month rates.
