### ISSUE TITLE
currency conversion

### ISSUE THREAD

**Issue by eadmaster** [exchangeratesapi/exchangeratesapi#25]
is it possible to perform currency conversion like the old Google Finance API:
`https://www.google.com/finance/converter?a=1&from=EUR&to=USD`
?

**Comment by madisvain** [comment]
@eadmaster you can perform currency conversions by changing the base currency.

https://api.exchangeratesapi.io/latest?base=EUR&symbols=USD

**Comment by eadmaster** [comment]
ok, but can i pass an amount to convert to the API?

**Comment by madisvain** [comment]
@eadmaster no the API is just for exchange rates. The calculations with amounts should be done in your own codebase.
