### ISSUE TITLE
What about exchange rates on weekends?

### ISSUE THREAD

**Issue by Sweeper777** [exchangeratesapi/exchangeratesapi#26]
I am trying to display a graph of exchange rates of the past 30 days. I know there is no data on weekends but when I try to request something like:

https://api.exchangeratesapi.io/2018-11-18?base=USD&symbols=JPY

I get the rates for 2018-11-16.

So can I get this behaviour for requesting over a time period? For example:

https://api.exchangeratesapi.io/history?start_at=2018-10-20&end_at=2018-11-18&symbols=JPY&base=USD

Currently I only get 20 rates, instead of 30. Can the rates on weekends be provided as well? Just use the same value as the Friday before.

**Comment by madisvain** [comment]
@Sweeper777 this is something you can also do within your own code but I do agree that based on the example you provided it would be logical if the API behaved in such a way as you described. I can look into this and get back to you on this.

**Comment by pwrnrd** [comment]
@madisvain In my opinion it doens't make sense to add this as the API uses the ECB reference rates as a source. The ECB doesn't publicize these reference rates in weekends (/non-working days?). If you would allow this functionality then you must also form an opinion on the exchange rate on any given date. E.g. what is the most accurate reflection of the true exchange rate on a Sunday if I load data historically? Is it the exchange rate from the Friday before (two days ago) or the exchange rate from Monday (one day later)? Or perhaps its some kind of average or any other type of estimate? I think it would be wise to leave this up to the user to determine.

P.S. Thank you for creating and hosting this API!! Great work!!

**Comment by madisvain** [comment]
Closing this issue based on @pwrnrd comment. The reasons pointed out are valid and we will not be implementing weekend rates at this point in time and will leave it up to the user to decide how to calculate them.
