### ISSUE TITLE
exchangeratesapi.io does not return updated data

### ISSUE THREAD

**Issue by pwrnrd** [exchangeratesapi/exchangeratesapi#28]
**Request**
https://api.exchangeratesapi.io/2018-12-12?base=EUR&symbols=USD

**Response**

`{"date":"2018-12-07","rates":{"USD":1.1371},"base":"EUR"}`

**Expected Behaviour**

`{"date":"2018-12-12","rates":{"USD":1.1346},"base":"EUR"}`

**Description**
The data does not seem to be updated since Friday (2018-12-07).

**Comment by madisvain** [comment]
It's fixed.

It seems we have run out of disk space on our server. I will need to get log rotation into place and see what was piling up. Thank you for letting us know.

**Comment by pwrnrd** [comment]
Thank you!

**Comment by madisvain** [comment]
The issue has been resolved with log-rotate applied.

**Comment by NarayanB** [comment]
Hi,
Looks like it is happening again. The updated date hasn't changed, and is stuck at "2019-02-20"

**Comment by NarayanB** [comment]
Example: https://api.exchangeratesapi.io/latest?base=USD
Result:
{"base":"USD","date":"2019-02-20","rates":{"ISK":119.6438017986,.....

**Comment by madisvain** [comment]
Yes I resolved it for now and left the issue open until I check what happened.

**Comment by gauss345** [comment]
I'm having a similar issue, where be calls to , `https://api.exchangeratesapi.io/latest?base=USD` returns the same value, sometimes hours later. Is this an issue that will recur a lot, as we kind of depend on the accuracy of this value ?

**Comment by Adcreators** [comment]
I am using free account .It  redirects to http://api.exchangeratesapi.io/v1/latest?access_key ...and pops up currency conversion error....
![Screen Shot 2021-04-08 at 3 46 48 pm](https://user-images.githubusercontent.com/62326194/114109375-7c621680-9918-11eb-865b-574558f8ce89.png)
