### ISSUE TITLE
Exchange rates not up to date, stuck at 2019-01-23

### ISSUE THREAD

**Issue by Castellari** [exchangeratesapi/exchangeratesapi#31]
**Isue:**
Results seem to be stuck on 2019-01-23

**Request:**
https://api.exchangeratesapi.io/latest?base=EUR&symbols=USD

**Response:**
`{"rates":{"USD":1.1367},"base":"EUR","date":"2019-01-23"}`

**Expected response:**
`{"rates":{"USD":1.1397},"base":"EUR","date":"2019-01-25"}`

**Comment by madisvain** [comment]
The issue is resolved. I will look into what caused this and will get this resolved. Thank you letting me know and I will do my best to keep these issues from not repeating.
