### ISSUE TITLE
Exchange rates not up to date, stuck at 2019-02-20

### ISSUE THREAD

**Issue by NarayanB** [exchangeratesapi/exchangeratesapi#33]
Hi,
Looks like the issue has surfaced again. 
Query:   https://api.exchangeratesapi.io/latest?base=USD
Result:
{"base":"USD","date":"2019-02-20","rates":{"ISK":119.6438017986,

**Comment by madisvain** [comment]
It's currently resolved but I will leave this issue open until I can check what went wrong.
