### ISSUE TITLE
Currencies are different from Google

### ISSUE THREAD

**Issue by BrunoQuaresma** [exchangeratesapi/exchangeratesapi#34]
When I try to get USD -> BRL the value always is different from the base value on Google. Is it an issue?

**Comment by pwrnrd** [comment]
That depends on your application. The API exposes the ECB reference exchange rates. These reference rates are published on a daily basis. If your application requires exchange rate data on a higher interval (every hour/minute/etc.) this API might not be for you. However, if you're looking for a daily exchange rate and you can find yourself in the methodology that the ECB uses to determine the reference rates, than this API is excellent.

References:
ECB Methodology: https://www.ecb.europa.eu/stats/pdf/exchange/Frameworkfortheeuroforeignexchangereferencerates.en.pdf?c883afa875c74877fdf4634dcb85688c
