### ISSUE TITLE
Too many redirects when EUR is the base symbol

### ISSUE THREAD

**Issue by LefterisJP** [exchangeratesapi/exchangeratesapi#35]
Hello.

First of all thank you for this awesome service!

I noticed that starting from today if we do a GET request to `'https://api.exchangeratesapi.io/latest?base=EUR&symbols=USD'` it does not work, and you end up getting redirected forever.

On the other hand `'https://api.exchangeratesapi.io/latest?base=USD&symbols=EUR'` works fine.

**Comment by madisvain** [comment]
@LefterisJP currently you can just omit the base=EUR as EUR is the default base currency anyway.

**Comment by pagoda6644** [comment]
The title is written wrong, if you read his issue, the redirecting problem comes up when USD is the base.

**Comment by madisvain** [comment]
@LefterisJP @pagoda6644 but currently the link https://api.exchangeratesapi.io/latest?base=EUR&symbols=USD seems to be working without and redirection issues I think

**Comment by LefterisJP** [comment]
@madisvain yes I tihnk it works fine now. When I reported the issue it was not.
