### ISSUE TITLE
No new rates since 2019-03-20

### ISSUE THREAD

**Issue by johamm** [exchangeratesapi/exchangeratesapi#36]
Looks like the same issue has arisen (surprisingly on the same day of the month as last time):

https://api.exchangeratesapi.io/latest?base=GBP

Says: "date":"2019-03-20"

**Comment by madisvain** [comment]
@johamm the issue should currently be resolved

**Comment by johamm** [comment]
I can still see it saying 2019-03-20 - when should this update?

**Comment by madisvain** [comment]
Current response from https://api.exchangeratesapi.io/latest?base=GBP. Please see if the request is somehow cached for you.

```json
{
   "base":"GBP",
   "rates":{
      "BGN":2.2770986145,
      "NZD":1.913261148,
      "ILS":4.7529398067,
      "RUB":84.6926301083,
      "CAD":1.7644661777,
      "USD":1.3158691349,
      "PHP":69.0848760042,
      "CHF":1.3089998836,
      "AUD":1.8538828734,
      "JPY":145.0692746536,
      "TRY":7.3325183374,
      "HKD":10.3251833741,
      "MYR":5.348352544,
      "HRK":8.6363953895,
      "CZK":29.9534288043,
      "IDR":18682.7104435906,
      "DKK":8.6880894167,
      "NOK":11.2263360112,
      "HUF":368.1802305274,
      "GBP":1.0,
      "MXN":24.967633019,
      "THB":41.6730702061,
      "ISK":157.5270695075,
      "ZAR":18.9159389917,
      "BRL":5.0948888113,
      "SGD":1.7773896845,
      "PLN":4.9962743043,
      "INR":90.7649318896,
      "KRW":1493.5498893934,
      "RON":5.5309116312,
      "CNY":8.8331586913,
      "SEK":12.1926883223,
      "EUR":1.1642798929
   },
   "date":"2019-03-22"
}
```

**Comment by johamm** [comment]
If I open the URL in an incognito tab in my browser, I'm getting the same response (with the 2019-03-20 date).  If I add "&1" at the end of the URL, it changes to look like yours.  Again, this is all in incognito so there's no caching involved.

Also, the date that's on the response you've sent shows it's still 3 days out.

**Comment by madisvain** [comment]
ECB does not release new exchange rates during the weekend so the latest rate is from the 22. thats correct. The rates for this week will come available in ~4 hours.

I attach a request for your reference with your exact URL without any additional parameters.
<img width="1103" alt="Screenshot 2019-03-25 12 07 44" src="https://user-images.githubusercontent.com/727994/54911284-cecd6780-4ef6-11e9-96ad-2184de259acb.png">

**Comment by johamm** [comment]
Sorry, didn't realise about the weekend bit!  As I can't see the correct data without putting the extra bit on the URL, I'll change my script to do that for now and hope it'll fix the issue on my end.
