### ISSUE TITLE
latest not working. browser returns too many redirects

### ISSUE THREAD

**Issue by abarke** [exchangeratesapi/exchangeratesapi#42]
NOK https://api.exchangeratesapi.io/latest
OK https://api.exchangeratesapi.io/latest?symbols=USD,GBP

Status is not picking up this error: https://stats.uptimerobot.com/Q6z9gTYrY

**Comment by madisvain** [comment]
@abarke can you please check your setup because I can see no redirect.

![Screenshot 2019-04-25 22 34 26](https://user-images.githubusercontent.com/727994/56763153-56ceb780-67aa-11e9-988b-e96e5a952f22.png)

**Comment by abarke** [comment]
![image](https://user-images.githubusercontent.com/34715541/56763417-aad59e00-67a2-11e9-8b68-7e6761bbfd54.png)

**Comment by abarke** [comment]
Same result on my phone (4G network)... too many redirects

**Comment by gaetano78** [comment]
Same here, but with base equal to USD. This is not working: 

https://api.exchangeratesapi.io/latest?base=USD
