### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by ciarlystreet** [exchangeratesapi/exchangeratesapi#46]
Hi,
I keep getting this error when trying to access your APIs

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.exchangeratesapi.io/latest?base=EUR. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)
```

My script:
```  
async asyncData({ $axios, error, params }) {
    try {
       const { data } = await $axios.get(
        'https://api.exchangeratesapi.io/latest',
        {
          params: {
            base: 'EUR'
          }
        }
      )
      const rates = data.rates
      })
      return {
        rates
      }
    } catch (e) {
      error({
        statusCode: 503,
        message: 'API connection error'
      })
    }
  }
```

**Comment by madisvain** [comment]
@ciarlystreet I tested it with a CORS testing site: https://www.test-cors.org/

It seems everything is correct and it loads just fine. Can you please take a look at your implementation.
<img width="1600" alt="Screenshot 2019-05-25 12 02 36" src="https://user-images.githubusercontent.com/727994/58367213-53336b00-7ee5-11e9-9508-fd6eb7d963c9.png">

**Comment by technoknol** [comment]
@madisvain I'm using Axios in React, it's calling OPTIONS requests first. And there's an error. Any suggestions for this ?

**Comment by CaddyDz** [comment]
I got around the issue with a proxy, you should still fix it tho 
```javascript
axios
	.get(
		"https://cors-anywhere.herokuapp.com/https://api.exchangeratesapi.io/latest?symbols=USD"
	)
	.then(response => {
		this.exchangeRate = response.data.rates.USD;
	});
```
