### ISSUE TITLE
Cannot search with TWD currency

### ISSUE THREAD

**Issue by JasonXDDD** [exchangeratesapi/exchangeratesapi#48]

**Comment by fawazahmed0** [comment]
I created an API , it does has TWD, if you still interested, it can be access from here:
https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1/latest/currencies/twd.json

The API is Free & No Rate Limits, with 150+ currencies, rates are updated daily

More info about API is available here:
https://github.com/fawazahmed0/currency-api

Thanks
