### ISSUE TITLE
Missing dates when requesting historic data

### ISSUE THREAD

**Issue by Budski** [exchangeratesapi/exchangeratesapi#52]
Hi, i'm having an issue where calling the historic data doesnt return all of the day between the two dates.

For example if i call this: https://api.exchangeratesapi.io/history?start_at=2018-02-02&end_at=2018-02-10&base=USD&symbols=GBP,EUR

It doesn't return all of the days between those two dates.

Am i missing something?

**Comment by wenusch** [comment]
Afaik the API doesn't provide rate changes during the weekend. 2018-02-03 and 2018-02-04 is a weekend.
