### ISSUE TITLE
Requesting Currency List Endpoint

### ISSUE THREAD

**Issue by DragonOsman** [exchangeratesapi/exchangeratesapi#56]
I'd really like it if I could request a list of currencies from the API itself.  I need this in my app because I want to populate two dropdown menus with the list of currencies: one for the base currency and the other for the currency to convert to.

**Comment by MarcelloTheArcane** [comment]
Use `Object.keys(res.data.rates)`

**Comment by madisvain** [comment]
@MarcelloTheArcane thank you very much for this answer.

Or you can also hardcode the currencies list from: https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html
