### ISSUE TITLE
Need to know the supporting currencies of the api.exchangeratesapi.io API. 

### ISSUE THREAD

**Issue by sureshvigneshbe** [exchangeratesapi/exchangeratesapi#57]
Kindly provide the list of currencies supporting this API.

**Comment by MarcelloTheArcane** [comment]
"CAD", "HKD", "ISK", "PHP", "DKK", "HUF", "CZK", "GBP", "RON", "SEK", "IDR", "INR", "BRL", "RUB", "HRK", "JPY", "THB", "CHF", "EUR", "MYR", "BGN", "TRY", "CNY", "NOK", "NZD", "ZAR", "USD", "MXN", "SGD", "AUD", "ILS", "KRW", "PLN"

**Comment by madisvain** [comment]
@MarcelloTheArcane thank you for the answer. Also the list of currencies on ECB website is correct.
https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html
