### ISSUE TITLE
Latest Rates are dated 1 day behind

### ISSUE THREAD

**Issue by ghronkrepps** [exchangeratesapi/exchangeratesapi#64]
As of Tuesday 10/29 the date has been one day behind.
For example:
Rates on Tuesday 10/29 are dated 10/28.
Rates on Wednesday 10/30 are dated 10/29.

This is different than in the past and just started happening.

**Comment by madisvain** [comment]
@ghronkrepps please note the ECB updates rates ~16-17. Currently it is already showing the 10/30 rates like they are supposed to.

I'm not sure about the exact timing the ECB published the rates today but this seems to be correct.

**Comment by ghronkrepps** [comment]
I suppose European DST is affecting this since European DST happens 5 days before US. We have pulled the rates for months now at 15:30 and they have always been updated at that time. It wasn't until this week that they seem to be behind by one hour. I will have to adjust our time by an hour for this interim period.
