### ISSUE TITLE
No weekend exchange rates?

### ISSUE THREAD

**Issue by ash-jc-allen** [exchangeratesapi/exchangeratesapi#66]
Hi,

I'm not entirely sure if this is an issue or just me not understanding something. I can't seem to get any exchange rates for dates on weekends. For example, using the following URL for 2019-11-10, I am returned the results for 2019-11-08:
```https://api.exchangeratesapi.io/2019-11-10?&base=EUR```

```
{
  "rates": {
    "CAD": 1.4561,
    "HKD": 8.6372,
    "ISK": 137.7,
    "PHP": 55.809,
    "DKK": 7.4727,
    "HUF": 333.37,
    "CZK": 25.486,
    "AUD": 1.6065,
    "RON": 4.7638,
    "SEK": 10.7025,
    "IDR": 15463.05,
    "INR": 78.652,
    "BRL": 4.5583,
    "RUB": 70.4653,
    "HRK": 7.4345,
    "JPY": 120.72,
    "THB": 33.527,
    "CHF": 1.0991,
    "SGD": 1.5002,
    "PLN": 4.261,
    "BGN": 1.9558,
    "TRY": 6.3513,
    "CNY": 7.7115,
    "NOK": 10.0893,
    "NZD": 1.7426,
    "ZAR": 16.3121,
    "USD": 1.1034,
    "MXN": 21.1383,
    "ILS": 3.8533,
    "GBP": 0.86158,
    "KRW": 1276.66,
    "MYR": 4.5609
  },
  "base": "EUR",
  "date": "2019-11-08"
}
```

Thanks in advance :)

**Comment by madisvain** [comment]
Hello - This API exposes the exchange rates from the European Central Bank. Those are reported only on workdays.

You can read more about it on https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html
