### ISSUE TITLE
Please add Afghani exchange rates

### ISSUE THREAD

**Issue by bosphoran** [exchangeratesapi/exchangeratesapi#81]
We would like to see Afghani exchange rates

**Comment by madisvain** [comment]
Sorry we only support the exchange rates provided by the European Central bank.

**Comment by fawazahmed0** [comment]
@bosphoran  I created an API , it does has AFN, if you are interested, it can be access from here:
https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1/latest/currencies/afn.json

The API is Free & No Rate Limits, with 150+ currencies, rates are updated daily

More info about API is available here:
https://github.com/fawazahmed0/currency-api

Thanks
